# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [21]:
import numpy as np
arr=np.random.randint(1,21,size=(5,5))

In [22]:
arr

array([[ 5,  7, 18, 13, 15],
       [ 7,  9,  3,  5, 19],
       [16, 16, 20, 17, 15],
       [11,  4, 10,  9,  7],
       [ 6,  3,  7,  2, 17]], dtype=int32)

In [ ]:
arr[:,2]=1
arr

array([[10, 14,  1,  5,  8],
       [ 7, 13,  1, 10, 15],
       [16, 11,  1, 14, 10],
       [ 3,  9,  1, 18,  4],
       [ 4,  9,  1, 20, 10]], dtype=int32)

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [ ]:
arr=np.arange(1,17)
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
np.fill_diagonal(arr,0)

In [33]:
arr

array([[ 0,  7, 18, 13, 15],
       [ 7,  0,  3,  5, 19],
       [16, 16,  0, 17, 15],
       [11,  4, 10,  0,  7],
       [ 6,  3,  7,  2,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [34]:
arr=np.arange(1,37).reshape(6,6)

In [35]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [37]:
arr[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [38]:
arr=np.arange(1,26).reshape(5,5)

In [39]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
border_element=(np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1])))
print(border_element)

[ 1  2  3  4  5 21 22 23 24 25  6 11 16 10 15 20]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [86]:
arr1=np.random.randint(1,11,size=(3,4))
arr2=np.random.randint(1,11,size=(3,4))

addition=arr1+arr2
subtraction=arr1-arr2
multiplication=arr1*arr2
division=arr1/arr2
print(addition)
print(subtraction)
print(multiplication)
print(division)

[[14 14 14  8]
 [18  9  8 12]
 [ 8 14  6  6]]
[[ 2  4  6  2]
 [-2  1  0  2]
 [ 2 -6  2 -2]]
[[48 45 40 15]
 [80 20 16 35]
 [15 40  8  8]]
[[1.33333333 1.8        2.5        1.66666667]
 [0.8        1.25       1.         1.4       ]
 [1.66666667 0.4        2.         0.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [98]:
print(arr)
arr=np.arange(1,17).reshape(4,4)
row_sum=np.sum(arr,axis=1)
col_sum=np.sum(arr,axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [96]:
print(row_sum)

[10 26 42 58]


In [97]:
print(col_sum)

[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [110]:
arr=np.random.randint(1,36, size=(5,5))
print(arr)

[[16 23 24  4 14]
 [29  1 18 25 10]
 [17 30 35 34 23]
 [27 12  2 21 22]
 [17 19 28  9 32]]


In [108]:
mean=np.mean(arr)
median=np.median(arr)
standard_div=np.std(arr)
variance=np.var(arr)

In [109]:
print(mean)
print(median)
print(standard_div)
print(variance)

18.8
22.0
9.273618495495704
86.0


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [111]:
arr = np.arange(1, 10).reshape((3, 3))

In [113]:
mean=np.mean(arr)
standard_div=np.std(arr)
normalized_arr=(arr-mean)/standard_div


In [114]:
print(mean)
print(standard_div)
print(normalized_arr)

5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
