## Numpy 
#### NumPy was created in 2005 by Travis Oliphant.
#### Numpy is a fundamental library for scientific computing in python.
####  It provides support foe arrays and matrices, along with a collection of mathematical functions to operate on these data structure. 

In [5]:
import numpy as np

## create array using numpy 
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns



array([[1, 2, 3, 4, 5]])

In [12]:
arr2=np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [ ]:
## 2D array
arr2=np.array([[1, 2, 3, 4, 5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])

print(arr) 
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [24]:
## Numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition
print("additon",arr1+arr2)

## Element wise substraction 
print("substraction",arr1-arr2)

## Element wise multiply
print("multiply",arr1*arr2)

## Element wise divide
print("divide",arr1/arr2)

additon [11 22 33 44 55]
substraction [ -9 -18 -27 -36 -45]
multiply [ 10  40  90 160 250]
divide [0.1 0.1 0.1 0.1 0.1]


In [25]:
## Universal function
arr=np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponent
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [27]:
## Array slicing and indexing 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [46]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [47]:
## Modify array elemets
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [48]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [49]:
## Statistical concepts-- Normalization
## To have a mean of 0 and standard deviation of 1 
data=np.array([1,2,3,4,5])

## Calculate the mean and standard deviation 
mean=np.mean(data)
std_div=np.std(data)

## Normalize the data 
normalized_data=(data-mean)/std_div
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [5]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean=np.mean(data)
print(mean)

## Median 
median=np.median(data)
print(median)

## Standard deviation
std_div=np.std(data)
print(std_div)

## Variance
variance=np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [56]:
## Logical Operation 
data=np.array([1,2,3,4,5,6,7,8,9,10])
#print(data>5)
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [2]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35, 40])
print(arr[::2])


[10 20 30 40]


In [19]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)        # identity matrix
np.arange(1, 10, 2)
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
print(a.ndim)   # dimensions
print(a.shape)  # shape
print(a.size)   # total elements
print(a.dtype)  # data type


3
(1, 3, 4)
12
int64


In [20]:
x = np.array([10, 20, 30])

print(x + 5)
print(x * 2)
print(np.mean(x))
print(np.sum(x))
print(np.max(x))
print(np.min(x))


[15 25 35]
[20 40 60]
20.0
60
30
10


In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)


[[1 2 3]
 [4 5 6]]
